version: '3'
services:
  nginx:
    build: 
      context: ./Nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./log:/var/log/nginx
    ports:
      - 90:80
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - nginx_ntw

  server1:
    build:
      context: ./Server1
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: server1
    networks:
      - nginx_ntw
  
  server2:
    build:
      context: ./Server2
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: server2
    networks:
      - nginx_ntw
  
  server3:
    build:
      context: ./Server3
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: server3
    networks:
      - nginx_ntw

networks:
  nginx_ntw:
    driver: bridge
